#!/usr/bin/env bash

# Install dependencies
case "$1" in
	arch*)
		pacman -Sy --needed --noconfirm base-devel \
										cmake \
										clang \
										libc++ \
										git \
										python \
										openssl \
										perl
		;;
	ubi*)
		dnf groupinstall -y "C Development Tools and Libraries"
		dnf install -y cmake \
						clang \
						git \
						libcxx \
						libcxx-static \
						libcxxabi-static \
						openssl-devel \
						perl
		;;
	*)
		apt update || true
		# https://stackoverflow.com/a/44333806
		if ! dpkg -l tzdata > /dev/null; then
			ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
			DEBIAN_FRONTEND=noninteractive apt install -y tzdata
			dpkg-reconfigure --frontend noninteractive tzdata
		fi
		apt install -y ca-certificates \
						build-essential \
						cmake \
						clang \
						libc++-dev \
						libc++abi-dev \
						git \
						python3 \
						libtool \
						automake \
						autoconf \
						pkgconf \
						openssl \
						libssl-dev
	;;
esac

# Build libcrypto.a (3.3)
if [ -z "$(find /usr -name libcrypto.a)" ]; then
	# allow static libs on Arch
	sed -i 's/!staticlibs/staticlibs/g' /etc/makepkg.conf &> /dev/null || true
	# fix perl's bin not being in $PATH on Arch
	source /etc/profile &> /dev/null || true
	git clone --depth=1 https://github.com/openssl/openssl -b openssl-3.3
	cd openssl
	./config
	make -j$(nproc --all) build_libs
	mkdir -p /usr/local/lib
	cp libcrypto.a /usr/local/lib
	cd ../
else
	echo "libcrypto.a exists. Skipping..."
fi

if [ -n "$CI" ] && [ -d "$PWD/.git" ]; then
	git config --global --add safe.directory $PWD
fi
