#!/bin/bash

set -e
shopt -s extglob

info() { echo "[info] $1"; }

ROOT="${PWD}"
STAGING="${ROOT}/staging"
PACKAGES="${ROOT}/packages"
export INSTALLPREFIX="${STAGING}/linux/iphone"

info "Creating prefix dir"
rm -rf "${STAGING}"
mkdir -p "${INSTALLPREFIX}"

info "Building libtapi"
cd "${ROOT}/apple-libtapi"
./build.sh
./install.sh
make -C "${ROOT}/apple-libtapi/build" install-tapi

info "Building cctools"
cd "${ROOT}/cctools-port/cctools"
./configure \
	--prefix="${INSTALLPREFIX}" \
	--with-libtapi="${INSTALLPREFIX}" \
	--target="aarch64-apple-darwin14" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-z,origin"
make
make install

info "Modifying toolchain"
cd "${INSTALLPREFIX}/bin"
for file in *; do
	mv "${file}" "${file#aarch64-apple-darwin14-}"
done

info "Installing ldid"
# TODO: Maybe build ldid ourselves?
curl -#L "https://github.com/sbingner/ldid/releases/download/v2.1.4%2B16.g5b8581c/ldid-linux.gz" | tar -xzf - -C "${INSTALLPREFIX}/bin"

info "Packaging toolchain"
mkdir -p "${PACKAGES}"
cd "${STAGING}"
tar -czf "${PACKAGES}/darwin-tools.tar.gz" linux

info "Done!"
