#!/usr/bin/env bash

set -e
shopt -s extglob

info() { echo "[info] $1"; }

ROOT="${PWD}"
VENDOR="${ROOT}/vendor"
STAGING="${ROOT}/staging"
PACKAGES="${ROOT}/packages"
export INSTALLPREFIX="${STAGING}/prefix/linux/iphone"
if [[ -x $(command -v nproc) ]]; then
	export JOBS=$(nproc --all)
elif [[ -x $(command -v sysctl) ]]; then
	export JOBS=$(sysctl -n hw.ncpu)
else
	export JOBS=1
fi

info "Creating prefix dir"
mkdir -p "${INSTALLPREFIX}"
rm -rf "${INSTALLPREFIX}"

info "Building LLVM tools"
mkdir -p "${STAGING}/build/"
cd "${STAGING}/build/"
cmake -B libtapi -S "${VENDOR}/apple-libtapi/src/llvm" \
	-DLLVM_ENABLE_PROJECTS="tapi;clang" \
	-DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DCMAKE_CXX_FLAGS="-I${PWD}/../src/llvm/projects/clang/include -I${PWD}/projects/clang/include" \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="${INSTALLPREFIX}"
cmake --build libtapi --target install-libtapi install-tapi-headers install-tapi install-dsymutil -- -j "${JOBS}"

info "Building libdispatch"
cmake -B libdispatch -S "${VENDOR}/apple-libdispatch" \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="$INSTALLPREFIX"
cmake --build libdispatch --target install

info "Building cctools"
mkdir -p "${STAGING}/build/cctools"
cd "${STAGING}/build/cctools"
"${VENDOR}/cctools-port/cctools/configure" \
	--prefix="${INSTALLPREFIX}" \
	--with-libtapi="${INSTALLPREFIX}" \
	--with-libdispatch="${INSTALLPREFIX}" \
	--with-libblocksruntime="${INSTALLPREFIX}" \
	--target="aarch64-apple-darwin14" \
	--program-prefix="" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-rpath,'\$\$ORIGIN/../lib64' -Wl,-z,origin"
make -j "${JOBS}" \
	PROGRAM_PREFIX="" \
	CXXABI_LIB="-l:libc++abi.a" \
	install

info "Building libplist"
cd "${VENDOR}/libplist"
PLIST_PREFIX="${STAGING}/libplist-install"
mkdir -p "${PLIST_PREFIX}" "${STAGING}/build/libplist"
LC_ALL=C NOCONFIGURE=1 ./autogen.sh
cd "${STAGING}/build/libplist"
LC_ALL=C "${VENDOR}/libplist/configure" --prefix="${PLIST_PREFIX}" --without-cython --enable-static --disable-shared PACKAGE_VERSION=latest
make -j "${JOBS}" install
cp -av "${PLIST_PREFIX}/bin/plistutil" "${INSTALLPREFIX}/bin"

info "Building ldid"
cd "${VENDOR}/ldid"
make -j "${JOBS}" \
	DESTDIR="${INSTALLPREFIX}" PREFIX="" \
	LIBCRYPTO_LIBS="-lcrypto -lpthread -ldl" \
	LIBPLIST_LIBS="${PLIST_PREFIX}/lib/libplist-2.0.a" LIBPLIST_INCLUDES="-I${PLIST_PREFIX}/include" \
	install

info "Packaging toolchain"
mkdir -p "${PACKAGES}"
tar -czf "${PACKAGES}/darwin-tools.tar.gz" -C "${STAGING}/prefix" linux

info "Done!"
