#!/usr/bin/env bash

set -e
shopt -s extglob

info() { echo "[info] $1"; }

ROOT="${PWD}"
STAGING="${ROOT}/staging"
PACKAGES="${ROOT}/packages"
export INSTALLPREFIX="${STAGING}/prefix/linux/iphone"
if [[ -x $(command -v nproc) ]]; then
	export JOBS=$(nproc --all)
elif [[ -x $(command -v sysctl) ]]; then
	export JOBS=$(sysctl -n hw.ncpu)
else
	export JOBS=1
fi

info "Creating prefix dir"
mkdir -p "${INSTALLPREFIX}"
rm -rf "${INSTALLPREFIX}"

info "Building LLVM tools"
mkdir -p "${STAGING}/build/apple-libtapi"
cd "${STAGING}/build/apple-libtapi"
cmake "${ROOT}/apple-libtapi/src/llvm" \
	-DCMAKE_CXX_FLAGS="-I${PWD}/../src/llvm/projects/clang/include -I${PWD}/projects/clang/include" \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DLLVM_ENABLE_PROJECTS="tapi;clang" \
	-DCMAKE_INSTALL_PREFIX="${INSTALLPREFIX}"
make clangBasic -j "${JOBS}"
make libtapi dsymutil install-libtapi install-tapi-headers install-dsymutil -j "${JOBS}"

info "Building libdispatch"
mkdir -p "${STAGING}/build/apple-libdispatch"
cd "${STAGING}/build/apple-libdispatch"
cmake "${ROOT}/apple-libdispatch" \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="$INSTALLPREFIX"
make -j "${JOBS}" install

info "Building cctools"
mkdir -p "${STAGING}/build/cctools"
cd "${STAGING}/build/cctools"
"${ROOT}/cctools-port/cctools/configure" \
	--prefix="${INSTALLPREFIX}" \
	--with-libtapi="${INSTALLPREFIX}" \
	--with-libdispatch="${INSTALLPREFIX}" \
	--with-libblocksruntime="${INSTALLPREFIX}" \
	--target="aarch64-apple-darwin14" \
	--program-prefix="" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-z,origin"
make -j "${JOBS}" \
	PROGRAM_PREFIX="" \
	CXXABI_LIB="-l:libc++abi.a" \
	install

info "Building libplist"
cd "${ROOT}/libplist"
PLIST_PREFIX="${STAGING}/libplist-install"
mkdir -p "${PLIST_PREFIX}" "${STAGING}/build/libplist"
LC_ALL=C NOCONFIGURE=1 ./autogen.sh
cd "${STAGING}/build/libplist"
LC_ALL=C "${ROOT}/libplist/configure" --prefix="${PLIST_PREFIX}" --without-cython PACKAGE_VERSION=latest
make -j "${JOBS}" install

info "Building ldid"
cd "${ROOT}/ldid"
make -j "${JOBS}" \
	DESTDIR="${INSTALLPREFIX}" PREFIX="" \
	LIBCRYPTO_LIBS="-l:libcrypto.a -lpthread -ldl" \
	LIBPLIST_LIBS="${PLIST_PREFIX}/lib/libplist-2.0.a" LIBPLIST_INCLUDES="-I${PLIST_PREFIX}/include" \
	install

info "Packaging toolchain"
mkdir -p "${PACKAGES}"
cd "${STAGING}/prefix"
tar -czf "${PACKAGES}/darwin-tools.tar.gz" linux

info "Done!"
